version: '3.9'

services:
  webapp-study:
    build:
      context: docker-context/webapp-study
    restart: always
    working_dir: /webapp-study
    networks:
      - study
    volumes:
      - "./webapp-study:/webapp-study"
    ports:
      - "8081:8080"


networks:
  study: